### PR TITLE
Add capability to build rules from category modules.

### PR DESCRIPTION
**Pull request by aekeus**
Each modules retrieves its ruleset asynchronously to allow future loading from a datastore.
- Add categories of publisher rules
- Add test verifying structure of categories
- Add tool to rebuild rules

Auditors: @mrose17, @bbondy

Test plan:

  `node tools/build-rules.js` will output complete ruleset

### CODE REVIEW

**Review by mrose17 — COMMENTED** [review]
let me suggest the following:

rather than have a list of modules in rules.js, just have it require every file there,, e.g., using `fs.readdir` with a basic sanity check that the file name ends ".js" and isn't "index.js" -- i would then move rules.js to "categories/index.js" directory and have the package simply require `__dirname + '/' + index.js` (or whatever)

does that make sense?

**Comment by aekeus** [comment]
Yes, that makes perfect sense. Will update. Thanks.

**Comment by mrose17** [comment]
hi. three things:
1. on startup, shouldn't index.js do something to invoke `require('categories').all() ? or is there another way you suggest?
2. my guess is that  if we are going to have a default rule, it should either be called `999-default.js` or be automatically added by `categories/index.js`
3. i was hoping that the sites in the "top 100" category be put into their respective functional units based on what each kind of site is. we don't exclude the alexa top 100 (many sites there are allowed).

thanks,

/mtr

**Comment by aekeus** [comment]
1. Yes, I was thinking of doing exactly this - except that the module is used by both the vault and the browser. I wonder if we want to do this on both sides?
2. Ok, makes sense.
3. Yes, if no one has any issue with the spreadsheet I shared earlier I can move the publishers into their respective categories.

**Comment by mrose17** [comment]
1. Ledger and the browser both use it, and the browser only on initialization.  So, probably have them do different things, and just have this package just export a function that calls all and updates the internal rules.
2. Please do so!

**Comment by mrose17** [comment]
many thanks. looks good to me!

**Pull request merged**
